Fix `'\'` being rendered as ’' on docs.rs
rust-bio/rust-bio-types pull request #31
Opened 2021-11-15 14:21 UTC by RagnarGrootKoerkamp

Before, this would render as two quotes since the `\` escapes the closing quote. Escaping the backslach itself should fix this.

Could also add `(a single backslash)` to clarify it for those reading the source instead of the online docs.

2021-11-16 06:26 UTC, dcroote requested changes
> Could also add `(a single backslash)` to clarify it for those reading the source instead of the online docs.

I think this would be helpful. Otherwise nice catch 👍

2021-11-17 07:55 UTC, RagnarGrootKoerkamp commented
@dcroote Done!

2021-11-17 08:17 UTC, dcroote approved these changes

2021-11-17 08:18 UTC, dcroote commented
LGTM!

2021-11-17 08:18 UTC, merged